name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main  # o la rama que uses para producción

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'  # o la versión que uses

    - name: Install dependencies
      run: |
        cd FrontEnd
        npm install

    - name: Build frontend
      run: |
        cd FrontEnd
        npm run build

    - name: Deploy to Firebase
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
      run: |
        npm install -g firebase-tools
        firebase deploy --only hosting
